### ISSUE TITLE
Timeseries vs realtime charts

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vue-stats#1]
I see that the chart type here is being set to 'realtime': https://github.com/digitalbazaar/bedrock-vue-stats/blob/initial/TimeSeriesChart.vue#L140

This seems to be working nicely for the realtime dashboard use case.  However, we have another use case that involves loading static data (stored realtime stats) into a chart.

Can the existing realtime charts be made to static (non-moving) timeseries charts by simply changing the chartjs chart type?  If so great, I guess we just need to allow the type to be passed as a prop/param.  If not, maybe we need another chart class?

**Comment by aljones15** [comment]
changing it straight out does actually break the graph, but there has to be a way of turning it out so will look into it. Also the history of the last commit in initial had to be rewritten so the author email is the digital bazaar one. so be sure to repull. same code just had to change one author on the last commit. switched to linux.

**Comment by aljones15** [comment]
@mattcollier bad news on this front.
Basically chartjs-realtime-plugin's api states the following:

```
Due to historical reasons, a chart with the 'time' scale will also auto-scroll if this plugin is enabled. If you want to stop scrolling a particular chart, set options.plugins.streaming to false.
```
I have tried disabling using this following options

```
options: {
  plugins: {
    streaming: false,
    'chartjs-plugin-streaming': false,
    'plugin-streaming': false,
  }
},
config: {
  plugins: {
    streaming: false,
    'chartjs-plugin-streaming': false,
    'plugin-streaming': false,
  }
}
```
in all cases it fails if the type is line and if the type is realtime the chart does not scroll however it throws this error:

```
type: realtime
Uncaught TypeError: Cannot read property 'lastMouseEvent' of undefined
```

```
type: line
TypeError: Cannot read property 'getPixelForValue' of undefined
```

Good news:
```
Old data will be automatically deleted after the time specified by the ttl option, or as it disappears off the chart.
```
so with real time stale data is removed automatically.

only solution so far is when realtime is false
1. do not show the pause button
2. freeze a realtime chart in place (pause it)

I have also tried unregistering the plugin globally and then just using it inline which is also causing the chart to error.

believe it not realtime plugin appears to ignore the xAxis display property too which means that we can not hide it from view.

chartjs-realtime-plugin also auto registers itself globally on import (which is really annoying).

**Comment by aljones15** [comment]
@mattcollier current code in the branch fixes this issue. Will reference this in a PR and close when code is merged in.

**Comment by aljones15** [comment]
the code is in initial so going to close it now. We might need to refactor Static vs realtime charts into separate modules in the future if we continue to add new features.
